eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 935377012
    url: jdbc:mysql://127.0.0.1/SpringCloud_shell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
server:
  port: 8003
